# Generated by Django 5.1.5 on 2025-03-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('princy', models.CharField(max_length=50)),
                ('pno', models.CharField(max_length=50)),
                ('add', models.CharField(max_length=50)),
            ],
        ),
    ]
